### ISSUE TITLE
Updating texture keeps increasing buffer size.

### ISSUE THREAD

**Issue by ron-adam** [datoviz/datoviz#76]
When using the dvz.upload_tex() function, datoviz increases the buffers used until around 4GB, then starts producing errors.
There are also some validation errors when using the debug build.
I think 4GB corresponds to my video cards shared buffer size.

Other notes:
     Coordinate systems could be more consistent.  This was a confusing point for me.  (May be for others.)  See the comments below.

     Functions possibly should accept tuples (or iterables) for small function arguments. 
   
Here's the program I'm testing with.  A modified version of the image example.
I've rearranged things a bit to better see how part are dependent on each other for my understanding.  (Not an issue.)

```python
"""
    Data-Image
    Testing updating an image from a numpy array.
"""
from pathlib import Path
import numpy as np
from PIL import Image

import datoviz as dvz
from datoviz import A_, vec2, vec3, vec4, uvec3


# Load a PNG image.
CURDIR = Path(__file__).parent
filepath = CURDIR / "../data/textures/image.png"
with Image.open(filepath) as f:
    image = np.array(f.convert('RGBA'), dtype=np.uint8)
    height, width = image.shape[:2]

# Setup top level contexts.
app = dvz.app(0)
batch = dvz.app_batch(app)
scene = dvz.scene(batch)

# Create a window with a panel to draw in.
figure = dvz.figure(scene, 1280, 720, dvz.CANVAS_FLAGS_FPS)
panel = dvz.panel_default(figure)

# Add an interactive camera to panel.
pz = dvz.panel_panzoom(panel)

# Create an image visual.
visual = dvz.image(batch, dvz.IMAGE_FLAGS_RESCALE)
dvz.image_alloc(visual, 1)

# Size of image in figure.
dvz.image_size(visual, 0, 1, vec2(width, height), 0)

# Position of image anchor in panel.
# (-1, -1) is lower left corner.
# (0, 0) is center.
# (1, 1) is upper right corner.
dvz.image_position(visual, 0, 1, vec3(0, 0, 0), 0)

# Normalized anchor point within image, origin: upper-left is (0,0).  center is (.5, .5)
dvz.image_anchor(visual, 0, 1, vec2(.5, .5), 0)

# Normalize texture sample coordinates. origins: upper-left is (0,0)  lower-right is (1,1)
tex_coords = np.array([[0,0,1,1]], dtype='f')
dvz.image_texcoords(visual, 0, 1, tex_coords, 0)    # vec4 doesn't work here?

# Create a texture for the visual to hold the image.
format = dvz.FORMAT_R8G8B8A8_UNORM
tex = dvz.tex_image(batch, format, height, width, None)  # Data updated below.

# Set how texture will be sampled, add to image visual.
filter = dvz.FILTER_LINEAR
address_mode = dvz.SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER
dvz.image_texture(visual, tex, filter, address_mode)

# Add the visual to the panel.
dvz.panel_visual(panel, visual, 0)


# Will be called when timer idx is 0.
def update_tex(t):
    # Simulating a video/data source.
    # Vary brightness so we can see image is updating.
    # Frames may be from external source. (Not about brightness.)
    brightness = .75 + np.cos(t % (2 * np.pi))/4
    tex_image = (image * brightness).astype('uint8')
    dvz.upload_tex(batch, tex, uvec3(), uvec3(), image.size, A_(tex_image), 0)


# Timer callback.
@dvz.timer
def on_timer(app, window_id, ev):
    update_tex(ev.time)

dvz.app_ontimer(app, on_timer, None)
dvz.app_timer(app, 0.5, 1/90, 0)


# Run the application.
dvz.scene_run(scene, app, 0)

dvz.scene_destroy(scene)
dvz.app_destroy(app)
```

**Comment by rossant** [comment]
Thank you! That's very helpful. I'll have a look soon. The API and conventions can certainly be improved at such an early stage where we can still easily break compatibility without disrupting too much code out there.

**Comment by ron-adam** [comment]
It was the dvz.image_position() coordinates from the lower right (-1,-1) that I found odd.  The only advantage I see for -1 to 1 positioning from lower right is the default of (0,0) is the center position.  But then other things gets harder.  Matching two different coordinate systems and scales for anchors and positions is not a good recipe.

Having the image position, and anchor position use the same 0.0 to 1.0 coordinates makes sense to me.

Setting both the anchor and image position to (.5, .5) will center the image.  Setting both to (0, 0) will move it to upper left corner.  And it works for the other corners as well.  Position(.5, 0) with anchor(.5, 0) is a top centered image.

I did a search to see how other programs do it in python.  Only came up with tk examples with directional anchors.  I think Matplotlib does that also.

**Comment by rossant** [comment]
For all visuals including the image visual, the position is in the same 3D coordinate system `[-1..1]^3`.

The decision for the image visual was to set (1) a point in the 3D space in that coordinate system and (2) an anchor that describes which point within the image should be at that point in the 3D space. We can decide the coordinate system of the anchor.

Here are a few cases with the position (fixed by the global coordinate system used across all visuals). You can make a proposition of what the anchor should be in each case.

* centered: position = (0, 0)
* top left corner: position = (-1, +1)
* top right corner: position = (+1, +1)
* lower left corner: position = (-1, -1)
* lower right corner: position = (+1, -1)

**Comment by ron-adam** [comment]
That info helps.  And thank you for correcting me.   (This will be a documentation issue then.)

But I wonder.  Looks like the anchors are not limited to be in the image, but can be outside it too.  Then maybe they 2D objects should have 3D anchors?   a (+- )z value will move it forward and back.   There's also a matter of orientation to the object, and orientation to the camera.   Are rotations done around anchors, or positions?   

 I'm just thinking out loud as I sort these ideas out in my head.  I'm not expecting answers to all of this.

By the way, the throughput of the texture updates to image seems fairly good even with the errors.   Looks promising.

**Comment by ron-adam** [comment]
Is there a way to get the current size of panels and images?

Looking at app_onresize for defining an on_resize callback.  I'm not seeing how to get the size's of objects to base a resize operation on.  


I've noticed that the visuals have many visual specific functions added,  where in python they would be class methods.  Is that a design choice in general, or something that will change?  I can see it working if the number of visuals don't get too large.  But I think that may limit Datoviz later on.

**Comment by rossant** [comment]
> But I wonder. Looks like the anchors are not limited to be in the image, but can be outside it too. Then maybe they 2D objects should have 3D anchors? a (+- )z value will move it forward and back. There's also a matter of orientation to the object, and orientation to the camera. Are rotations done around anchors, or positions?

I think the idea is that the image comes with its own local 3D coordinate system, with a reference that we choose to be at the center of the image, or one corner or whatever (this will have to be carefully determined and documented). Then, the "position" of the image visual will correspond to that reference. If the image visual supports rotation, it would be around that center. The existing specification of the image visual can and should certainly be improved in this regard.

**Comment by rossant** [comment]
> I've noticed there are many visual specific functions, where in python they would be class methods. Is that a design choice in general, or something that will change? I can see it working if the number of visuals don't get too large. But I think that may limit Datoviz later on.

Datoviz is a C-first library in that it provides a C API that does not support object-oriented programming. That is why there is 1 function per pair (visual, attribute type). The number of visuals is not expected to grow significantly (I don't think it will be much higher than 10-20 eventually). More sophisticated visuals may be implemented in Python on top of the primitive visuals supported by Datoviz.

The ctypes API is an automatically-generated thin wrapper of the C API, which is why it is not object-oriented. There are no plans to provide a higher-level Pythonic API on top of it *in Datoviz*.

**However**, the main goal of the VisPy 2.0 project I've been working on with @rougier is to provide such a Pythonic, matplotlib-like scientific plotting API on top of an intermediate-level protocol that is being built on top of Datoviz, among other renderers. That's what most end-users will use eventually.

I don't expect the Datoviz Python ctypes API that you're using right now to be much used eventually, because it is quite low-level for most use-cases.

**Comment by ron-adam** [comment]
> I think the idea is that the image comes with its own local 3D coordinate system, with a reference that we choose to be at the center of the image, or one corner or whatever (this will have to be carefully determined and documented). Then, the "position" of the image visual will correspond to that reference. If the image visual supports rotation, it would be around that center. The existing specification of the image visual can and should certainly be improved in this regard.

This should probably work the same for all/most visuals.  Then it's no longer a special case.  dvz.visual_anchor(visual, pos) will just work.  

I was thinking the normalized (-1,1) xyz range would be a minimal box size for the visual.  But that runs into problems for 2D shapes.   Then again, maybe it's not a problem, it just means the third axis would be ignored for 2D anchor positions.  Any value will be on the surface. (?)  

How these are used should determine how they are defined.  I'm still not familiar enough with all the parts yet.  Is there a python version of the davoviz demo?  I so, I haven't found it yet.   I also don't see tests for the python API.

**Comment by rossant** [comment]
That makes sense.

`dvz.demo()` will run the demo that is implemented in C.
The `examples` folder contains some Python demos.
There is only a single dummy test for Python right now, in `datoviz/tests.py`.

**Comment by ron-adam** [comment]
Yes, I've looked at those examples.

I was asking about the demo because it is a more complex example.    I wanted to see how it would work in Python.   I should be able to reproduce it by looking in the demo.c file.   (If all the needed routines are exposed in python.)

The reason Iasked about the tests, is that those may be an area I can contribute to Datoviz.  I think I can possibly look at the Vispy test suit as an example.  (Unless you have something else in mind.)

Any ideas how to stop the buffer from getting too big when updating the texture?  Or maybe there is another approach for sending video images to a datoviz panel quickly?

**Comment by rossant** [comment]
> The reason Iasked about the tests, is that those may be an area I can contribute to Datoviz. I think I can possibly look at the Vispy test suit as an example. (Unless you have something else in mind.)

I think the main thing with the Python tests would be that the bindings work on a few examples, typically by generating a screenshot and ensuring it more or less matches a reference image.

To test the Datoviz logic itself, it's all done in C at the moment. It might be interesting to write more tests in Python though, as they would be easier to maintain than C tests. Your contributions would be welcome!

**Comment by rossant** [comment]
I'll look at this soon. I think it's a bug in Datoviz, your code seems correct.

**Comment by rossant** [comment]
Short answer is that this should be fixed on `dev`.

Longer answer below, for future reference!

Texture uploads require an intermediate "staging buffer" on the GPU where data is sent to, before the data is copied from the staging buffer to the image (data cannot be uploaded directly to an image in Vulkan).

There are two possibilities for this staging buffer (which should have the same size of the texture if we want to copy in a single pass): it could be persistent, or not.

By default, it is not persistent, meaning that, at every image upload, a block of memory is allocated in a special common staging buffer. This block of memory being non persistent, it should be deallocated after the upload is complete. That part was missing! That's what I fixed in the commit, which should fix your bug.

If the staging buffer is persistent, then the staging buffer remains allocated on the GPU, which avoids allocating/deallocating it at every texture upload, but this consumes 2x more GPU VRAM. It is a tradeoff between memory usage and performance, depending on the size and frequency of the texture uploads.

Another fix in your example would have been to use:

```python
tex = dvz.tex_image(batch, format, height, width, None, dvz.TEX_FLAGS_PERSISTENT_STAGING)
```

to indicate that the created texture should have a persistent staging buffer, which might be better if you plan to constantly upload to it. However, the `dvz.tex_image()` function was not accepting a `flags` argument (it was an oversight). I also fixed this on `dev`. In your specific example, I would recommend that you use this flag.

**Comment by ron-adam** [comment]
Great, I'll try it out tonight.  Thank you.

**Comment by ron-adam** [comment]
Yes, it fixes the memory problem.   Still getting an error and warnings on every update.

```
09:15:56.669 T0 W C:\Users\ra-dev\Documents\datoviz\src\vkutils.h:0183: validation layer: Validation Warning: [ BestPractices-ImageBarrierAccessLayout ] Object 0: handle = 0x8cc1d80000000045, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0xf35d019f | vkCmdPipelineBarrier(): pImageMemoryBarriers[0] image is VkImage 0x8cc1d80000000045[] and accessMask is VK_ACCESS_2_MEMORY_READ_BIT, but for layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL expected accessMask are VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT|VK_ACCESS_2_SHADER_READ_BIT|VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT|VK_ACCESS_2_SHADER_SAMPLED_READ_BIT|VK_ACCESS_2_SHADER_STORAGE_READ_BIT|VK_ACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHR.
09:15:56.670 T0 E C:\Users\ra-dev\Documents\datoviz\src\vkutils.h:0183: validation layer: Validation Error: [ SYNC-HAZARD-WRITE-RACING-READ ] Object 0: handle = 0x24dc6dc5e10, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xccb77929 | vkQueueSubmit():  Hazard WRITE_RACING_READ for entry 0, VkCommandBuffer 0x24db565d090[], Submitted access info (submitted_usage: SYNC_IMAGE_LAYOUT_TRANSITION, command: vkCmdPipelineBarrier, seq_no: 1, VkImage 0x8cc1d80000000045[], reset_no: 374). Access info (prior_usage: SYNC_FRAGMENT_SHADER_SHADER_SAMPLED_READ, read_barriers: VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT, queue: VkQueue 0x24dc6caea80[], submit: 182, batch: 0, batch_tag: 2192, command: vkCmdDraw, command_buffer: VkCommandBuffer 0x24db565e9a0[], seq_no: 2, reset_no: 3).
```

**Comment by rossant** [comment]
Yes, I think that's unrelated. There are a bunch of Validation warnings/errors on some platforms. I'll tackle them separately. Despite these messages, does your example work as expected?

**Comment by ron-adam** [comment]
Yes it does, but possibly slower than it might without the errors.  Ok, so we can close this issue then.
